### ISSUE TITLE
Does not work - always fails with cannot create Rest Client

### ISSUE THREAD

**Issue by markussiebert** [cdktf/cdktf-cdk8s#130]
maybe related to https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/217 ?

always fails with ```bash
          │ Error: Failed to construct REST client
          │ 
          │   with kubernetes_manifest.Cdk8sApply_Cdk8sApply-metalsiderodev--v1alpha1-ServerClass-proxmox-vm-default_0C20A47B (Cdk8sApply/Cdk8sApply-metal.sidero.dev--v1alpha1-ServerClass-proxmox-vm-default),
          │   on cdk.tf.json line 121, in resource.kubernetes_manifest.Cdk8sApply_Cdk8sApply-metalsiderodev--v1alpha1-ServerClass-proxmox-vm-default_0C20A47B (Cdk8sApply/Cdk8sApply-metal.sidero.dev--v1alpha1-ServerClass-proxmox-vm-default):
          │  121:       }
          │ 
          │ cannot create REST client: no client config
```

my config looks like 

```ts
  console.log(kubeconfig.filename)
  new CDK8sProvider(this, 'Cdk8sApply', {
    cdk8sApp: cdk8sApp,
    configPath: path.join(__dirname, '../kubeconfig/sidero-single-node'),
    configContext: 'admin@SideroTalosCluster',
  });
```

**Comment by DanielMSchmidt** [comment]
Yeah seems to be this issue: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1775

**Comment by markussiebert** [comment]
But in my case, there is no reference or lookup - just plain link to config_file. 

Any ideas?

My config looks like:

```ts
"provider": {
    "kubernetes": [
      {
        "alias": "cdktf-cdk8s-Cdk8sApply",
        "config_path": "/Users/.../github/lab/kubeconfig/sidero-single-node",
        "insecure": true
      }
    ],
    "sops": [
      {
      }
    ]
  },
```

**Comment by markussiebert** [comment]
Ok, got it - the created provider was never used, because you set an alias. With this small change it works on my machine!
