### ISSUE TITLE
Tokenized Variables in strings are not fully resolving

### ISSUE THREAD

**Issue by joekiller** [cdktf/cdktf-cdk8s#286]
### Description

As a user I expect a [Terraform Function in CDK](https://developer.hashicorp.com/terraform/cdktf/concepts/functions), such as [tonumber](https://developer.hashicorp.com/terraform/language/functions/tonumber), to resolve when utilized within a construct rendered by the CDK8sProvider. 

Actual behavior: the [Token](https://developer.hashicorp.com/terraform/cdktf/concepts/tokens) is resolved from a float to a variable however no further resolution takes place leaving the symbol in an un-interpolated `${} HCL interpolation syntax` format, [Interpolation](https://developer.hashicorp.com/terraform/language/expressions/strings#interpolation).

![Screenshot 2024-09-06 at 11 21 53 AM](https://github.com/user-attachments/assets/c14d20e5-1240-49fe-b0ca-eaf30024c583)

I created a test demonstrating the defect here: https://github.com/joekiller/cdktf-cdk8s/commit/c4c66120e37bfc6d8200bdff0626a5c1df8aaf49

### Versions

cdktf debug
language: typescript
cdktf-cli: 0.20.8
node: v20.11.1
cdktf: 0.20.8
constructs: 10.3.0
jsii: null
terraform: 1.9.4
arch: arm64
os: darwin 23.6.0
providers
random@ ~> 3.6.2 (LOCAL)
        terraform provider version: 3.6.2
@cdktf/provider-google-beta (PREBUILT)
        terraform provider version: 5.38.0 
        prebuilt provider version: 13.20.0
        cdktf version: ^0.20.0
@cdktf/provider-google (PREBUILT)
        terraform provider version: 5.38.0 
        prebuilt provider version: 13.27.0
        cdktf version: ^0.20.0
@cdktf/provider-helm (PREBUILT)
        terraform provider version: 2.14.1 
        prebuilt provider version: 10.2.1
        cdktf version: ^0.20.0
@cdktf/provider-kubernetes (PREBUILT)
        terraform provider version: 2.31.0 
        prebuilt provider version: 11.6.0
        cdktf version: ^0.20.0

running `npm list`

dexcom-cdk@1.0.0 /Users/jl0918/src/github/dexcom-inc/dexcom-cdk
├── @cdktf/provider-google-beta@13.20.0
├── @cdktf/provider-google@13.27.0
├── @cdktf/provider-helm@10.2.1
├── @cdktf/provider-kubernetes@11.6.0
├── @eslint-community/eslint-utils@4.4.0
├── @eslint/compat@1.1.1
├── @eslint/js@9.6.0
├── @google-cloud/secret-manager@5.6.0
├── @types/eslint__js@8.42.3
├── @types/jest@29.5.12
├── @types/node@20.14.10
├── cdk8s-plus-29@2.5.4
├── cdk8s@2.68.97
├── cdktf-cdk8s@0.10.34
├── cdktf-cli@0.19.2
├── cdktf@0.20.8
├── constructs@10.3.0
├── eslint-config-prettier@9.1.0
├── globals@15.8.0
├── husky@9.0.11
├── jest@29.7.0
├── jsii-pacmak@1.102.0
├── jsii@5.4.31
├── keychain@1.5.0
├── prettier@3.3.3
├── ts-jest@29.2.2
├── ts-node@10.9.2
├── typescript-eslint@7.16.0
├── typescript@5.5.3
└── utility-types@3.11.0

### Providers

───────────┬─────────────────────┬─────────┬─────────────────────┬─────────────┐
───         ───           ─       ──        ───────               ───
 Provider  │ Provider      CDKTF │         │ Package Name        │ Package     │
Name        Version               Constraint                      Version
───────────┼─────────────────────┼─────────┼─────────────────────┼─────────────┤
───         ───           ─       ──        ───────               ───
 random    │ 3.6.2               │  ~> 3.6.│                     │             │

───────────┼─────────────────────┼─────────┼─────────────────────┼─────────────┤
───         ───           ─       ──        ───────               ───
 google-bet│ 5.38.0        ^0.20.│         │ @cdktf/provider-goog│ 13.20.0     │
                                            e-beta

───────────┼─────────────────────┼─────────┼─────────────────────┼─────────────┤
───         ───           ─       ──        ───────               ───
 google    │ 5.38.0        ^0.20.│         │                     │ 13.27.0     │
                                            @cdktf/provider-google

───────────┼─────────────────────┼─────────┼─────────────────────┼─────────────┤
───         ───           ─       ──        ───────               ───
 helm      │ 2.14.1        ^0.20.│         │ @cdktf/provider-helm│ 10.2.1      │

───────────┼─────────────────────┼─────────┼─────────────────────┼─────────────┤
───         ───           ─       ──        ───────               ───
 kubernetes│ 2.31.0        ^0.20.│         │ @cdktf/provider-kube│ 11.6.0      │
                                            netes

───────────┴─────────────────────┴─────────┴─────────────────────┴─────────────┘
───         ───           ─       ──        ───────               ───

### Possible Solutions

I wonder if the [Only run once](https://github.com/cdktf/cdktf-cdk8s/blob/c63dee4767dbdc672ca0da244d40f019dad30ff6/src/index.ts#L55-L56) clause of the aspect is blocking the final run of resolution.

### References

- https://github.com/cdktf/cdktf-cdk8s/issues/192

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
Your assumption is incorrect in this case. CDKTF functions render hcl functions, that's their intended purpose. We don't expose a good way to do this other than functions.

**Comment by joekiller** [comment]
@DanielMSchmidt I did take a guess at the cause. I'm sorry I'm not as familiar with the framework.

Can you confirm that it is expected that the final output after being applied is expected go from

```
ports: [{ containerPort: Fn.tonumber("8080") }]
```

to

```
ports: [{ containerPort: "${tonumber(\"8080\")}" }]
```

versus becoming

```
ports: [{ containerPort: 8080 }]
```

When I deployed via cdktf deploy, it didn't apply the function. How is the function supposed to resolve otherwise.

Thanks for your patience and insight.

**Comment by DanielMSchmidt** [comment]
Yes that's expected. The function stays during synth and terraform will apply it during plan / apply
